name: Publish Pinboard annotations

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *' # every hour, at ~:30 https://crontab.guru/#30_*_*_*_*

jobs:
  crosspost-pinboard-links:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Pull Node packages
      run: |-
        npm install
    - name: Fetch latest data
      run: |-
        node _scripts/generate-link-posts.mjs
      env:
        PINBOARD_API_TOKEN: ${{ secrets.PINBOARD_API_TOKEN }}
    - name: Commit and push if there are new links
      run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add _links/*.md
          timestamp=$(date -u)
          git commit -m "Latest links from Pinboard: ${timestamp}" || exit 0
          git push